apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: t5s16dsra-nodejs-gitops
  description: This is GitOps manifest for t5s16dsra-nodejs   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-selector: rhtap/gitops=t5s16dsra-nodejs
    backstage.io/kubernetes-id: t5s16dsra-nodejs 
    backstage.io/techdocs-ref: dir:. 
    janus-idp.io/tekton: t5s16dsra-nodejs
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:t5s16dsra-nodejs
