apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: t5s16dsra-nodejs
  janus-idp.io/tekton: t5s16dsra-nodejs
  backstage.io/kubernetes-id: t5s16dsra-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: t5s16dsra-nodejs
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
