apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: t5s16dsra-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: t5s16dsra-nodejs 
  name: t5s16dsra-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: t5s16dsra-nodejs 
